env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 30
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: alacritty
    # General application class
    general: alacritty

  #gtk_theme_variant: None

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000
  auto_scroll: true

#tabspaces: 8

font:
  normal:
    family: Space Mono
    style: Medium

  bold:
    family: Space Mono
    style: Bold

  italic:
    family: Space Mono
    style: Italic

  bold_italic:
    family: Space Mono
    style: Bold Italic

  # Point size
  size: 13

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true


# colors:
#   primary:
#     background: '#282828'
#     foreground: '#ebdbb2'

#   selection:
#     text: '#282828'

#   # Normal colors
#   normal:
#     black:   '#3c3836'
#     red:     '#cc241d'
#     green:   '#7f991a'
#     yellow:  '#d79921'
#     blue:    '#458588'
#     magenta: '#b16286'
#     cyan:    '#689d6a'
#     white:   '#a89984'

#   # Bright colors
#   bright:
#     black:   '#7c6f64'
#     red:     '#fb4934'
#     green:   '#95bb26'
#     yellow:  '#fabd2f'
#     blue:    '#83a598'
#     magenta: '#d3869b'
#     cyan:    '#8ec07c'
#     white:   '#ebdbb2'

colors:
  primary:
    background: '#131216'
    foreground: '#d7cdba'

  selection:
    text: '#131216'

  # Normal colors
  normal:
    black:   '#21232c'
    red:     '#f8524f'
    green:   '#87a4a0'
    yellow:  '#ffd089'
    blue:    '#843e42'
    magenta: '#f8524f'
    cyan:    '#87a4a0'
    white:   '#e0d8c9'

  # Bright colors
  bright:
    black:   '#403c4e'
    red:     '#f8524f'
    green:   '#87a4a0'
    yellow:  '#ffd089'
    blue:    '#843e42'
    magenta: '#f8524f'
    cyan:    '#87a4a0'
    white:   '#e0d8c9'


background_opacity: 1
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
