env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 30
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: alacritty
    # General application class
    general: alacritty

  #gtk_theme_variant: None

scrolling:
  history: 5000
  auto_scroll: true

tabspaces: 4

font:
  normal:
    family: Space Mono
    style: Medium

  bold:
    family: Space Mono
    style: Bold

  italic:
    family: Space Mono
    style: Italic

  bold_italic:
    family: Space Mono
    style: Bold Italic

  # Point size
  size: 13

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

schemes:
  rosepine: &rosepine
    primary:
      background: "#191724"
      foreground: "#e0def4"
    cursor:
      text: "#191724"
      cursor: "#796268"
    vi_mode_cursor:
      text: "#191724"
      cursor: "#796268"
    line_indicator:
      foreground: None
      background: None
    selection:
      background: "#2A2738"
    normal:
      black:    "#6e6a86"
      red:      "#eb6f92"
      green:    "#9ccfd8"
      yellow:   "#f6c177"
      blue:     "#31748f"
      magenta:  "#c4a7e7"
      cyan:     "#ebbcba"
      white:    "#e0def4"
    bright:
      black:    "#6e6a86"
      red:      "#eb6f92"
      green:    "#9ccfd8"
      yellow:   "#f6c177"
      blue:     "#31748f"
      magenta:  "#c4a7e7"
      cyan:     "#ebbcba"
      white:    "#e0def4"

  catppuccin: &catppuccin
    primary:
      background: '#1b1923'
      foreground: '#D9E0EE'

    cursor:
      text: '#1E1D2F'
      cursor: '#F5E0DC'

    normal:
      black:   '#6E6C7E'
      red:     '#F28FAD'
      green:   '#ABE9B3'
      yellow:  '#FAE3B0'
      blue:    '#96CDFB'
      magenta: '#F5C2E7'
      cyan:    '#89DCEB'
      white:   '#D9E0EE'

    bright:
      black:   '#988BA2'
      red:     '#F28FAD'
      green:   '#ABE9B3'
      yellow:  '#FAE3B0'
      blue:    '#96CDFB'
      magenta: '#F5C2E7'
      cyan:    '#89DCEB'
      white:   '#D9E0EE'

  indexed_colors:
    - { index: 16, color: '#F8BD96' }
    - { index: 17, color: '#F5E0DC' }

  blue_passion: &blue_passion
    primary:
      background: '#09090a'
      foreground: '#dddddd'
      
    selection: 
      background: '#546e7a'
      text: '#0a0a0b'

    normal:
      black:   '#18191C'
      red:     '#b59f8b'
      green:   '#5cbfdb'
      yellow:  '#d8cfbd'
      blue:    '#7f7f84'
      magenta: '#7f7f84'
      cyan:    '#7f7f84'
      white:   '#c6d6f2'

    bright:
      black:   '#191b25'
      red:     '#b59f8b'
      green:   '#5cbfdb'
      yellow:  '#d8cfbd'
      blue:    '#7f7f84'
      magenta: '#7f7f84'
      cyan:    '#7f7f84'
      white:   '#c6d6f2'

  spaceman: &spaceman
    primary:
      # background: '#131216'
      background: '#0f0e11'
      foreground: '#d7cdba'
    selection:
      text: '#131216'
    normal:
      black:   '#21232c'
      red:     '#f8524f'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'
    bright:
      black:   '#403c4e'
      red:     '#f8524f'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'

  base: &base
    primary:
      background: '#0e0d11'
      foreground: '#d7cdba'
    selection:
      text: '#131216'
    normal:
      black:   '#33303f'
      red:     '#bc413b'
      green:   '#908F70'
      yellow:  '#EDAB4D'
      blue:    '#5c4a5f'
      magenta: '#bc413b'
      cyan:    '#908F70'  # #376886 #6bb3a0
      white:   '#d3c4a2'
    bright:
      black:   '#33303f'
      red:     '#bc413b'
      green:   '#908F70'
      yellow:  '#EDAB4D'
      blue:    '#5c4a5f'
      magenta: '#bc413b'
      cyan:    '#908F70'
      white:   '#d3c4a2'
        
colors: *catppuccin

background_opacity: 1
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
