env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 50
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: alacritty
    # General application class
    general: alacritty

  #gtk_theme_variant: None

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000
  auto_scroll: true

#tabspaces: 8

font:
  normal:
    family: Jet Brains Mono
    style: Bold

  bold:
    family: Jet Brains Mono
    style: Bold

  italic:
    family: Jet Brains Mono
    style: Italic

  bold_italic:
    family: Jet Brains Mono
    style: Bold Italic

  # Point size
  size: 13

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

# colors:
#   # Horizon theme
#   primary:
#     background: '#1c1e20'
#     foreground: '#cbced0'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '#1c1e20'
#     cursor: '#cbced0'

#   # Normal colors
#   normal:
#     black:   '#1c1e20'
#     red:     '#d4637d'
#     green:   '#6dd092'
#     yellow:  '#dda68b'
#     blue:    '#51bfd5'
#     magenta: '#a86cd4'
#     cyan:    '#61bcbc'
#     white:   '#cbced0'

#   # Bright colors
#   bright:
#     black:   '#6f6f70'
#     red:     '#d4637d'
#     green:   '#6dd092'
#     yellow:  '#dda68b'
#     blue:    '#51bfd5'
#     magenta: '#a86cd4'
#     cyan:    '#61bcbc'
#     white:   '#e3e6ee'


colors:
  primary:
    background: '#050505'
    foreground: '#aaaaaa'

  selection:
    text: '#1c1c1b'

  # Normal colors
  normal:
    black:   '#050505'
    red:     '#b59f8b'
    green:   '#86baba'
    yellow:  '#dddddd'
    blue:    '#dddddd'
    magenta: '#dddddd'
    cyan:    '#86baba'
    white:   '#dddddd'

  # Bright colors
  bright:
    black:   '#050505'
    red:     '#b59f8b'
    green:   '#86baba'
    yellow:  '#dddddd'
    blue:    '#dddddd'
    magenta: '#dddddd'
    cyan:    '#86baba'
    white:   '#dddddd'


  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '0x000000'
  #  red:     '0x8c3336'
  #  green:   '0x7a8530'
  #  yellow:  '0x97822e'
  #  blue:    '0x506d8f'
  #  magenta: '0x80638e'
  #  cyan:    '0x497e7a'
  #  white:   '0x9a9a9a'

background_opacity: 0.9
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }

