env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 50
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

  #gtk_theme_variant: None

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000
  auto_scroll: true

#tabspaces: 8

font:
  normal:
    family: Sf Mono
    style: Bold

  bold:
    family: Sf Mono
    style: Bold

  italic:
    family: Sf Mono
    style: Italic

  bold_italic:
    family: Sf Mono
    style: Bold Italic

  # Point size
  size: 13

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x2c2c2b'
    foreground: '0xd5c4a1'

  selection:
    text: '0x2c2c2b'

  # Normal colors
  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xd4b398'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xf68b85'
    green:   '0xc7d28d'
    yellow:  '0xf5aa79'
    blue:    '0x9ecbc1'
    magenta: '0xe2b0bd'
    cyan:    '0xa3d7a8'
    white:   '0xe0deb6'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '0x000000'
  #  red:     '0x8c3336'
  #  green:   '0x7a8530'
  #  yellow:  '0x97822e'
  #  blue:    '0x506d8f'
  #  magenta: '0x80638e'
  #  cyan:    '0x497e7a'
  #  white:   '0x9a9a9a'

background_opacity: 0.9
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }

