env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 30
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: alacritty
    # General application class
    general: alacritty

  #gtk_theme_variant: None

scrolling:
  history: 5000
  auto_scroll: true

tabspaces: 4

font:
  normal:
    family: Space Mono
    style: Medium

  bold:
    family: Space Mono
    style: Bold

  italic:
    family: Space Mono
    style: Italic

  bold_italic:
    family: Space Mono
    style: Bold Italic

  # Point size
  size: 13

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

schemes:
  rosepine: &rosepine
    primary:
      background: "#191724"
      foreground: "#e0def4"
    cursor:
      text: "#191724"
      cursor: "#796268"
    vi_mode_cursor:
      text: "#191724"
      cursor: "#796268"
    line_indicator:
      foreground: None
      background: None
    selection:
      background: "#2A2738"
    normal:
      black:    "#6e6a86"
      red:      "#eb6f92"
      green:    "#9ccfd8"
      yellow:   "#f6c177"
      blue:     "#31748f"
      magenta:  "#c4a7e7"
      cyan:     "#ebbcba"
      white:    "#e0def4"
    bright:
      black:    "#6e6a86"
      red:      "#eb6f92"
      green:    "#9ccfd8"
      yellow:   "#f6c177"
      blue:     "#31748f"
      magenta:  "#c4a7e7"
      cyan:     "#ebbcba"
      white:    "#e0def4"

  passion: &passion
    primary:
      background: '#110813'
      foreground: '#dec7fa'
      
    selection: 
      background: '#dec7fa'
      text: '#110813'

    normal:
      black:   '#6e0727'
      red:     '#f30149'
      green:   '#87a4a0'
      yellow:  '#f6c177'
      blue:    '#034c7d'
      magenta: '#C03048'
      cyan:    '#C00048'
      white:   '#e0def4'

    bright:
      black:   '#6e0727'
      red:     '#f30149'
      green:   '#87a4a0'
      yellow:  '#f6c177'
      blue:    '#034c7d'
      magenta: '#C03048'
      cyan:    '#C00048'
      white:   '#e0def4'

  blue_passion: &blue_passion
    primary:
      background: '#070c1a'
      foreground: '#e1dae9'
      
    selection: 
      background: '#191b3f'
      text: '#070c1a'

    normal:
      black:   '#070c1a'
      red:     '#913a52'
      green:   '#cc9966'
      yellow:  '#e2b570'
      blue:    '#5791b1'
      magenta: '#9f3c91'
      cyan:    '#452060'
      white:   '#d0e2e8'

    bright:
      black:   '#291546'
      red:     '#913a52'
      green:   '#cc9966'
      yellow:  '#e2b570'
      blue:    '#5791b1'
      magenta: '#9f3c91'
      cyan:    '#452060'
      white:   '#d0e2e8'

  gruvbox: &gruvbox
    primary:
      background: '#282828'
      foreground: '#ebdbb2'

    selection:
      text: '#282828'

    normal:
      black:   '#3c3836'
      red:     '#fb4934'
      green:   '#7f991a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    bright:
      black:   '#7c6f64'
      red:     '#fb4934'
      green:   '#95bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  spaceman: &spaceman
    primary:
      background: '#131216'
      foreground: '#d7cdba'
    selection:
      text: '#131216'
    normal:
      black:   '#21232c'
      red:     '#f8524f'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'
    bright:
      black:   '#403c4e'
      red:     '#f8524f'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'
        
colors: *blue_passion


background_opacity: 1
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
