env:
  TERM: xterm-256color

window:
  #  columns: 0
  #  lines: 0

  padding:
    x: 30
    y: 6

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: alacritty
    # General application class
    general: alacritty

  #gtk_theme_variant: None

scrolling:
  history: 5000
  auto_scroll: true

tabspaces: 4

font:
  normal:
    family: Space Mono
    style: Medium

  bold:
    family: Space Mono
    style: Bold

  italic:
    family: Space Mono
    style: Italic

  bold_italic:
    family: Space Mono
    style: Bold Italic

  # Point size
  size: 11

  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

schemes:
  blue_passion: &blue_passion
    primary:
      background: '#09090a'
      foreground: '#dddddd'
      
    selection: 
      background: '#546e7a'
      text: '#0a0a0b'

    normal:
      black:   '#18191C'
      red:     '#b59f8b'
      green:   '#5cbfdb'
      yellow:  '#d8cfbd'
      blue:    '#7f7f84'
      magenta: '#7f7f84'
      cyan:    '#7f7f84'
      white:   '#c6d6f2'

    bright:
      black:   '#191b25'
      red:     '#b59f8b'
      green:   '#5cbfdb'
      yellow:  '#d8cfbd'
      blue:    '#7f7f84'
      magenta: '#7f7f84'
      cyan:    '#7f7f84'
      white:   '#c6d6f2'

  spaceman: &spaceman
    primary:
      # background: '#131216'
      background: '#0f0e11'
      foreground: '#d7cdba'
    selection:
      text: '#131216'
    normal:
      black:   '#21232c'
      red:     '#843e42'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'
    bright:
      black:   '#403c4e'
      red:     '#f8524f'
      green:   '#87a4a0'
      yellow:  '#ffd089'
      blue:    '#843e42'
      magenta: '#f8524f'
      cyan:    '#87a4a0'
      white:   '#e0d8c9'

  gruv: &gruv
    primary:
      background: '#1D2021'
      foreground: '#EBDBB2'
    selection:
      text: '#282828'
      background: "#D65D0E"
    normal:
      black:   '#504945'
      red:     '#FB4934'
      green:   '#98971A'
      yellow:  '#D79921'
      blue:    '#458588'
      magenta: '#B16286'
      cyan:    '#689D6A'
      white:   '#EBDBB2'
    bright:
      black:   '#504945'
      red:     '#FB4934'
      green:   '#98971A'
      yellow:  '#D79921'
      blue:    '#458588'
      magenta: '#B16286'
      cyan:    '#689D6A'
      white:   '#EBDBB2'

  test: &blackberry
    primary:
      background: '#130F13'
      # #171217 #1d161d #231a23 #251d25 #2e242e #362b36
      foreground: '#cbaa72'
    selection:
      text: '#0d3345' # #221f38
      background: "#F6CE8A"
    normal:
      black:   '#402A47'
      red:     '#6E264A' # #ac2048 #660033
      green:   '#8F934E'
      yellow:  '#d59410'
      blue:    '#654370'
      magenta: '#a56243'
      cyan:    '#395560' # #03899E
      white:   '#efd8a1'
    bright:
      black:   '#2E2848'
      red:     '#6B1A42'
      green:   '#8F934E'
      yellow:  '#d59410'
      blue:    '#573960'
      magenta: '#a56243'
      cyan:    '#395560'
      white:   '#efd8a1'
      
  hard: &warm
    primary:
      background: '#130F13'
      foreground: '#e1b473'
      # #1d161b #251d25
    selection:
      text: '#241c22'
      background: "#130F13"
    normal:
      black:   '#1d161b'
      red:     '#b24b50'
      green:   '#6b7d7a'
      yellow:  '#df8038'
      blue:    '#4f4965'
      magenta: '#c3523f'
      cyan:    '#6f3a53'
      white:   '#ffe0b2'
    bright:
      black:   '#443c42'
      red:     '#b24b50'
      green:   '#6b7d7a'
      yellow:  '#df8038'
      blue:    '#4f4965'
      magenta: '#c3523f'
      cyan:    '#6f3a53'
      white:   '#ffe0b2'
      
        
colors: *blackberry

window.opacity: 1
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
