#! /bin/sh

#              _            _             _   
#             | |          | |           | |  
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
                                             
picom -b & 
nitrogen --restore & 
/home/indigo/.config/polybar/launch.sh &
/home/indigo/Public/screen.sh &
setxkbmap -model abnt2 -layout br &
pgrep -x sxhkd > /dev/null || sxhkd &

#                        _ _             
#                       (_) |            
#  _ __ ___   ___  _ __  _| |_ ___  _ __ 
# | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__|
# | | | | | | (_) | | | | | || (_) | |   
# |_| |_| |_|\___/|_| |_|_|\__\___/|_|   

bspc monitor -d I II III IV

#  _                                                    __ _       
# | |                                                  / _(_)      
# | |__  ___ _ ____      ___ __ ___     ___ ___  _ __ | |_ _  __ _ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \   / __/ _ \| '_ \|  _| |/ _` |
# | |_) \__ \ |_) \ V  V /| | | | | | | (_| (_) | | | | | | | (_| |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  \___\___/|_| |_|_| |_|\__, |
#           | |                                               __/ |
#           |_|                                              |___/ 

bspc config border_width                  2
bspc config borderless_monocle            true
bspc config click_to_focus                false
bspc config window_gap                    12
bspc config top_padding                   25
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.55
bspc config single_monocle                false
bspc config gapless_monocle               true

#            _                
#           | |               
#   ___ ___ | | ___  _ __ ___ 
#  / __/ _ \| |/ _ \| '__/ __|
# | (_| (_) | | (_) | |  \__ \
#  \___\___/|_|\___/|_|  |___/

bspc config normal_border_color		      "#7f7f84"
bspc config active_border_color	        "#86baba"
bspc config focused_border_color	      "#b59f8b"
bspc config presel_feedback_color	      "#b59f8b"
bspc config urgent_border_color 	      "#ad2727"

#             _           
#            | |          
#  _ __ _   _| | ___  ___ 
# | '__| | | | |/ _ \/ __|
# | |  | |_| | |  __/\__ \
# |_|   \__,_|_|\___||___/

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a kitty state=floating
